export const usersList = [
  {
    userId: '1',
    email: 'john.doe@example.com',
    emailVerified: true,
    userName: 'john doe',
    picture: 'https://example.com/pictures/johndoe.jpg',
    title: 'Software Engineer',
    birthDate: '1990-01-15',
    phone: '+1234567890',
    address: '123 Main St, Springfield, IL',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '2',
    email: 'jane.smith@example.com',
    emailVerified: true,
    userName: 'jane smith',
    picture: 'null',
    title: 'Product Manager',
    birthDate: '1985-05-22',
    phone: '+0987654321',
    address: '456 Elm St, Metropolis, NY',
    gender: 'female',
    role: 'admin',
  },
  {
    userId: '3',
    email: 'alice.wonder@example.com',
    emailVerified: false,
    userName: 'ali cew',
    picture: 'https://example.com/pictures/alicew.jpg',
    title: 'null',
    birthDate: 'null',
    phone: 'null',
    address: 'null',
    gender: 'male',
    role: 'super admin',
  },
  {
    userId: '4',
    email: 'bob.builder@example.com',
    emailVerified: true,
    userName: 'bob',
    picture: 'null',
    title: 'Construction Manager',
    birthDate: '1975-11-30',
    phone: '+1122334455',
    address: '789 Oak St, Small town, TX',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '5',
    email: 'charlie.brown@example.com',
    emailVerified: false,
    userName: 'char lie',
    picture: 'https://example.com/pictures/charlieb.jpg',
    title: 'Graphic Designer',
    birthDate: '1992-07-10',
    phone: '+4455667788',
    address: '101 Pine St, Gotham, NJ',
    gender: 'male',
    role: 'user',
  },

  {
    userId: '7',
    email: 'edward.norton@example.com',
    emailVerified: true,
    userName: 'edward',
    picture: 'https://example.com/pictures/edwardn.jpg',
    title: 'Data Scientist',
    birthDate: '1988-09-12',
    phone: '+3344556677',
    address: '303 Cedar St, Metropolis, NY',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '8',
    email: 'fiona.gallagher@example.com',
    emailVerified: false,
    userName: 'fiona',
    picture: 'null',
    title: 'Marketing Specialist',
    birthDate: '1995-04-18',
    phone: '+1122334455',
    address: '404 Birch St, Chicago, IL',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '9',
    email: 'george.orwell@example.com',
    emailVerified: true,
    userName: 'george',
    picture: 'https://example.com/pictures/georgeo.jpg',
    title: 'Author',
    birthDate: '1903-06-25',
    phone: '+5566778899',
    address: '505 Walnut St, London, UK',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '10',
    email: 'hannah.montana@example.com',
    emailVerified: true,
    userName: 'hannah',
    picture: 'null',
    title: 'Singer',
    birthDate: '1993-11-23',
    phone: '+6677889900',
    address: '606 Spruce St, Los Angeles, CA',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '11',
    email: 'ian.fleming@example.com',
    emailVerified: false,
    userName: 'ian',
    picture: 'https://example.com/pictures/ianf.jpg',
    title: 'Writer',
    birthDate: '1908-05-28',
    phone: '+7788990011',
    address: '707 Oak St, London, UK',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '12',
    email: 'jessica.jones@example.com',
    emailVerified: true,
    userName: 'jessica',
    picture: 'null',
    title: 'Private Investigator',
    birthDate: '1985-12-01',
    phone: '+8899001122',
    address: '808 Pine St, New York, NY',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '13',
    email: 'kevin.mitnick@example.com',
    emailVerified: true,
    userName: 'kevin',
    picture: 'https://example.com/pictures/kevinm.jpg',
    title: 'Security Consultant',
    birthDate: '1963-08-06',
    phone: '+9900112233',
    address: '909 Maple St, Las Vegas, NV',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '14',
    email: 'laura.palmer@example.com',
    emailVerified: false,
    userName: 'laura',
    picture: 'null',
    title: 'Waitress',
    birthDate: '1972-04-22',
    phone: '+0011223344',
    address: '1010 Cedar St, Twin Peaks, WA',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '15',
    email: 'michael.scott@example.com',
    emailVerified: true,
    userName: 'michael',
    picture: 'https://example.com/pictures/michaels.jpg',
    title: 'Regional Manager',
    birthDate: '1965-03-15',
    phone: '+1122334455',
    address: '1111 Birch St, Scranton, PA',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '16',
    email: 'nancy.wheeler@example.com',
    emailVerified: true,
    userName: 'nancy',
    picture: 'null',
    title: 'Student',
    birthDate: '1971-06-05',
    phone: '+2233445566',
    address: '1212 Oak St, Hawkins, IN',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '17',
    email: 'oliver.queen@example.com',
    emailVerified: false,
    userName: 'oliver',
    picture: 'https://example.com/pictures/oliverq.jpg',
    title: 'CEO',
    birthDate: '1985-01-16',
    phone: '+3344556677',
    address: '1313 Pine St, Star City, WA',
    gender: 'male',
    role: 'admin',
  },
  {
    userId: '18',
    email: 'pam.beesly@example.com',
    emailVerified: true,
    userName: 'pam',
    picture: 'null',
    title: 'Receptionist',
    birthDate: '1979-03-25',
    phone: '+4455667788',
    address: '1414 Maple St, Scranton, PA',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '19',
    email: 'quentin.tarantino@example.com',
    emailVerified: true,
    userName: 'quentin',
    picture: 'https://example.com/pictures/quentint.jpg',
    title: 'Film Director',
    birthDate: '1963-03-27',
    phone: '+5566778899',
    address: '1515 Walnut St, Los Angeles, CA',
    gender: 'male',
    role: 'user',
  },
  {
    userId: '20',
    email: 'rachel.green@example.com',
    emailVerified: false,
    userName: 'rachel',
    picture: 'null',
    title: 'Fashion Designer',
    birthDate: '1969-12-11',
    phone: '+6677889900',
    address: '1616 Spruce St, New York, NY',
    gender: 'female',
    role: 'user',
  },
  {
    userId: '6',
    email: 'diana.prince@example.com',
    emailVerified: true,
    userName: 'diana',
    picture: 'null',
    title: 'CTO',
    birthDate: '1980-03-25',
    phone: '+9988776655',
    address: '202 Maple St, scira, WA',
    gender: 'female',
    role: 'admin',
  },
];
